version: "3"

services:
  profile-postgres:
    build: 
        context: .
        dockerfile: dockerfile-postgres
    container_name: profile-postgres
    environment:    
        - POSTGRES_PASSWORD=profile-test
        - POSTGRES_USER=profiler
        - POSTGRES_DB=test
    expose:
        - "5432"
    image: postgres
    ports:
        - "5432:5432"

  goapp:
    build: ./profile-go-microservice
    container_name: goapp-profiling
    expose: 
        - "5000"
    links:
        - profile-postgres
    ports:
        - "5000:5000"

  csharpapp-2:
    build: 
        context: ./profile-c-sharp-microservice
        dockerfile: dockerfile-2
    container_name: csharpapp-profiling-2
    expose:
        - "5001"
    links:
        - profile-postgres
    ports:
        - "5001:80"

  csharpapp-1-1:
    build: 
        context: ./profile-c-sharp-microservice
        dockerfile: dockerfile-1.1
    container_name: csharpapp-profiling-1-1
    expose:
        - "5002"
    links:
        - profile-postgres
    ports:
        - "5002:80"

# To run: docker-compose up -d
